Member request
polkadot-fellows/seeding pull request #12
Opened 2022-09-27 09:44 UTC by AurevoirXavier

Hi, I'm Xavier Lau. I am a core developer from Darwinia Network, having worked on Substrate and Polkadot ecosystem for the last three years.

I think I should be in the rank range of 3~4.

---

I'm:
- [top 0.82% this quarter](https://stackexchange.com/leagues/710/quarter/substrate/2022-07-01/251#251) on the substrate.stackexchange.
- the author of [array-bytes](https://github.com/hack-ink/array-bytes), and it's so proud to be a dependency of Substrate. [PR](https://github.com/paritytech/substrate/pull/12190)
- the author of [subalfred](https://github.com/hack-ink/subalfred). Its goal is to be an all-in-one Substrate development toolbox. And it gets some stars from the parity core developers. (thanks, guys)

I found:
- a non-deterministic behavior on Substrate. Due to security issues, @gavofyork suggests I delete the detail. So the [issue](https://github.com/paritytech/substrate/issues/6752) is empty.
- some weird code during the Polkadot code review and report to @kianenigma. [PR](https://github.com/paritytech/polkadot/pull/2562)

Most of the time I'm doing the code review. 
A little bit of shame, I don't have a lot of PRs contributions.

2022-09-27 16:58 UTC, rphmeier commented
Xavier,

You're a longstanding member of the community who I recognize as a major contributor to stackexchange and in developer chats. Still, the Fellowship at the moment is constrained to _core protocol contributions_, and in that respect I do not see enough of a record of contribution to merit III or IV Dan. I would suggest applying for II Dan and to proceed to III Dan with some deeper protocol contributions.

2022-09-28 01:53 UTC, AurevoirXavier commented
> Xavier,
> 
> Thanks for the request. You're a longstanding member of the community who I recognize as a major contributor to stackexchange and in developer chats. Still, the Fellowship at the moment is constrained to _core protocol contributions_, and in that respect I do not see enough of a record of contribution to merit III or IV Dan. I would suggest applying for I or II Dan and to re-evaluate after some deeper protocol contributions.
> 
> Quoting from III Dan requirements:
> 
> > As a foundational grade, a Fellow represents both a ceiling and a floor: becoming
> > a Fellow indicates the individual has enough knowledge and skill to build
> > substantial protocol components (i.e. all but the major protocol components,
> > e.g. a pallet or 2-10,000 line crate) alone and with high expectations that they
> > will be completed correctly and to a high standard

Done.

2022-09-29 11:10 UTC, jacogr requested changes, later dismissed

2022-09-29 11:10 UTC, jacogr commented on README.md
> +| Github Username     | Kusama Account ID                                 | Rank |
Sorry to be a pain on this. Could we leave the re-formatting out of this PR - it makes merging in main (things go in quite often there) and checking the actual changes quite laborious.

(I do understand that "beauty is in the eye of the beer-holder", but specifically for my checks here, the above changed-to-all creates a bit of chaos)

TL;DR I think the formatting changes could possibly pass as a "stand-alone" PR (with some discussion around it, i.e. GH output won't be affected), but here would leave it out in this PR.

2022-09-29 16:15 UTC, gavofyork approved these changes

2022-09-29 16:57 UTC, gavofyork requested changes
Mis-read and thought this was an application for I Dan - that I would back happily.

2022-09-29 17:01 UTC, jacogr commented
I'm a huge fan of the work I have been seeing, especially around the (mostly) thankless efforts on SE. 

Having said that, I'm also on agreement on a I Dan request.

Based on the II Dan requirements, I do feel we are missing the "assisted in implementing a major component" part of the requirement.

2022-09-29 17:18 UTC, jacogr approved these changes

2022-09-29 18:35 UTC, gavofyork approved these changes

2022-09-29 18:43 UTC, bkchr approved these changes

2022-09-29 18:49 UTC, andresilva approved these changes

2022-09-29 19:23 UTC, merged

2022-09-29 19:51 UTC, kianenigma commented
Late to the decision, but indeed wanted to appreciate numerous valuable and insightful bug reports that I have received from @AurevoirXavier over the years 👍