modified address
polkadot-fellows/seeding pull request #59
Opened 2022-11-21 11:04 UTC by seunlanlege

2022-11-21 11:07 UTC, rrtti approved these changes

2022-11-21 11:33 UTC, bkchr commented
The onchain entity of this account is Picasso, linked to composable. Are you really sure that you used the correct account?

2022-11-21 11:36 UTC, rrtti requested changes
Please provide a personal address, not Picasso's

2022-11-21 17:23 UTC, rrtti approved these changes

2022-11-21 21:05 UTC, bkchr approved these changes

2022-11-22 05:37 UTC, jacogr approved these changes

2022-11-22 12:04 UTC, gavofyork approved these changes

2022-11-22 12:04 UTC, merged